### PR TITLE
fix: build fail when first updown io downtime spans before 'from' date

### LINKED ISSUE #914: [BUG] Build fail because of /api/donnee page error
I have a lead, I'm going to investiguate.

### PR DESCRIPTION
**Pull request by johangirod**
fix #914

### CODE REVIEW

File: clients/monitoring/series.ts [hunk 1]
```diff
@@ -97,31 +100,35 @@ export class DailyUptimeRatioConverter {
...
+/**
+ *  For a given date, returns the Date of the next UTC day at 00:00:00
+ *  ex: 19/07/2021 14:35:00 UTC => 20/07/2021 00:00:00
+ *  */
+function getUTCNextDay(d: Date): Date {
+  const next = new Date(
+    Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate() + 1)
+  );
+  return next;
+}
```
Comment (johangirod) [inline clients/monitoring/series.ts:134]: I moved those pure functions outside class scope for readiness (we know they don't depend on class internal that way).

File: clients/monitoring/series.ts [hunk 2]
```diff
@@ -35,10 +34,13 @@ export class DailyUptimeRatioConverter {
   feed(downtimes: IUpdownIODowntimes[]) {
     for (let i = 0; i < downtimes.length; i++) {
       const downtime = downtimes[i];
+      let downStartDate = new Date(downtime.started_at);
 
-      const downStartDate = new Date(downtime.started_at);
+      if (downStartDate.getTime() < this._from.getTime()) {
+        downStartDate = this._from;
+      }
```
Comment (johangirod) [inline clients/monitoring/series.ts:41]: This is the interesting bit, the rest is noise, sorry.
