### PR TITLE
fix: remove cp_dep_type

### LINKED ISSUE #318: Filtres: fix
- `cp_dep_type` not being cleant
- visual glitch on close filter

### PR DESCRIPTION
**Pull request by XavierJp**
closes #318

### CODE REVIEW

File: components-ui/filter-menu/filter-menu.tsx [hunk 1]
```diff
@@ -32,27 +32,31 @@ export const FilterMenu: React.FC<PropsWithChildren<FilterMenuProps>> = ({
 
   const [open, setOpen] = useState(false);
 
-  const ref = useOutsideClick(() => {
+  const ref = useOutsideClick((e) => {
```
Comment (yoanficadiere) [inline components-ui/filter-menu/filter-menu.tsx]: `e` is not used

**Review by yoanficadiere — APPROVED** [review]
